### ISSUE TITLE
Streamer status Unknown

### ISSUE THREAD

**Issue by SchnitzelPommes** [Radioh/ha_twitch_helix#16]
Hello,
I set up this twitch integration added some streamers to my configuration it got the pictures of the streamer and as attribute it shows the channel views but the state of every channel is unknown no matter if they are streaming or not.
Did I do something wrong?

Thank you

**Comment by Radioh** [comment]
Hi,

It sounds like you have enabled the "stream" API opt out, which will make the component not request the stream data.
Remove the "stream" api out out from your config, and it should update the stream data. :)

**Comment by SchnitzelPommes** [comment]
Oh well yeah it works I understood the function the wrong way my bad.

Thank you for your work and your help
