### ISSUE TITLE
Subscribed Attribute wrong

### ISSUE THREAD

**Issue by kc3577** [Radioh/ha_twitch_helix#17]
all my subscribed channels are shown as false.
I entered my channel name and it says I'm following

**Comment by Radioh** [comment]
Hi, it sounds like you might not have the user:read:subscriptions or user_subscriptions scope.
Please add those scopes to your client application if you want to have those data available through the API.

You should be able to add those scopes to your application by following this: https://www.home-assistant.io/integrations/twitch/

**Comment by kc3577** [comment]
where do I enter the OAuth token? the entry token: does not allow Home Assistant with twitch_helix

**Comment by kc3577** [comment]
ok, took care of itself the token generator transfers it automatically

**Comment by kc3577** [comment]
ok, took care of itself the token generator transfers it automatically
