### ISSUE TITLE
Log flooding with warnings related to coroutines after HA Core update 2023.6

### ISSUE THREAD

**Issue by lichenophile** [Radioh/ha_twitch_helix#27]
`Logger: py.warnings
Source: custom_components/twitch_helix/sensor.py:182
Integration: twitch_helix (documentation)
First occurred: 14:46:22 (265 occurrences)
Last logged: 23:34:23

/config/custom_components/twitch_helix/sensor.py:182: RuntimeWarning: coroutine 'Twitch.check_user_subscription' was never awaited self._subscription = {`

**Comment by Radioh** [comment]
I think I identified the issue and have created a fix - #28 - I've updated the release to 1.0.1. Let me know if it doesn't work.
