### ISSUE TITLE
How do I obtain more values

### ISSUE THREAD

**Issue by NicciZar** [Radioh/ha_twitch_helix#4]
Hi,

I want to get the same values (or more) like the default twitch integration with Hassio.

There are some things missing..

This is how I obtain the values

`{{states.sensor.twitchstreamername.attributes}}`

and I'm getting

```
{
  "subscribed": false,
  "subscription_is_gifted": false,
  "following": true,
  "following_since": "2016-08-15T14:48:02Z",
  "friendly_name": "twitchstreamername",
  "icon": "mdi:twitch",
  "entity_picture": "https://static-cdn.jtvnw.net/jtv_user_pictures/1-profile_image-300x300.jpg"
}
```

before that (using the old sensor)

```
{
  "followers": XXX,
  "views": XXX,
  "friendly_name": "twitchstrreamername",
  "icon": "mdi:twitch",
  "entity_picture": "https://static-cdn.jtvnw.net/jtv_user_pictures/1-profile_image-300x300.jpg"
}
```

You see that there are some things missing (followers and views)

Is it still possible to obtain these with the new helix api and this integration?

**Comment by Radioh** [comment]
@NicciZar - I had some time and added an api_opt_outs list to the config, so we can opt out of Twitch API calls if we don't need all info.

**Comment by NicciZar** [comment]
Oh thats great! Thank you
